version: "3.9"

networks:
  default:
    name: ewenbouquet/jenkins-network

services:
  jenkins-service:
    image: ewenbouquet/jenkins:latest
    user: root
    privileged: true
    ports:
      - "8090:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_ADMIN_ID=${JENKINS_ADMIN_ID}
      - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD}

  nexus:
    image: sonatype/nexus3:latest
    ports:
      - "8091:8081"
    volumes:
      - ./nexus-data:/nexus-data

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=datacenter1
    logging:
      driver: none